global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  width: 25.0
  height: 25.0
  resolution: 0.1
  static_map: true
  rolling_window: false
  use_dijkstra: false
  track_unknown_space: true #
  transform_tolerance: 0.5 #latency fazla ise arttir
  
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
